name: My-First-Action
run-name: ${{ github.actor }} is writing Actions
jobs:
  check-hello-version:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a Hello World message
      - run: echo "Hello World"
      - name: Define variables and then echo them
        env:
          VARIABLEE_1: This_Is_Var_1
          VARIABLEE_2: This_is_var_2
        run: 
          echo $VARIABLEE_1
