name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  check-hello-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello World"
      - name: Define variables and then echo them
        env:
          VARIABLEE_1: This_Is_Var_1
          VARIABLEE_2: This_is_var_2
          VAR_1: 10
          VAR_2: 20
        run: 
          echo $VARIABLEE_1
          echo "This will be Var 2 - $VARIABLEE_2"
          Echo "It Is Working 1 ${{ env.VAR_2 > env.VAR_1}}"
      - name: Testing an expression
        run: Echo "It Is Working 2 ${{ env.VAR_2 > env.VAR_1}}"