name: Reusable Wprkflow

on:
    workflow_call:
        inputs:
            config-o-something:
              required: true
              type: string


jobs:
    Reusable-W-1:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello Reusable"
            - name: Print the config-o-something input
              run: echo ${{ inputs.config-o-something }}