name: Reusable Workflow

on:
    workflow_call:
        inputs:
            config-o-something:
              required: true
              type: string
            target:
                description: 'Deployment matrix'
                required: true
                type: string


jobs:
    Reusable-W-1:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello Reusable"
            - name: Print the config-o-something input
              run: echo ${{ inputs.config-o-something }}
            - name: Matrix
              run: echo ${{ inputs.target }}
    
    output-data:
        name: Generate output
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.outputs.firstword }}
        steps:
            - id: step1
              run: echo "firstword=hello" >> $GITHUB_OUTPUT

